In [1]:
import pandas as pd

reads = pd.read_parquet("/home/tds122/coaster/data/reads.parquet")

reads

         sample_idx                                           read_seq
0                 0  CACGGCGCUCUUCCGAUCUCCCGUAUCAACUUCGGUAUUGAAAAGG...
1                 0  CACGGCGCUCUUCCGAUCUCCCGUAUCAACUUCGGUAUUGAAAAGG...
2                 0  AAAAAAGUAGUUUUUUUAUUUUAUUUUGUUCGUUAAUUUUCAAUUU...
3                 0  AAAAAAGUAGUUUUUUUAUUUUAUUUUGUUCGUUAAUUUUCAAUUU...
4                 0  GACUGGGUAGGUUUCAGUUGGGUGGGCGGCUUGGAACAUGUAGUAU...
...             ...                                                ...
8654798        8836  CUCUUAGUCUCCCUACGCCUUGAUAAUAGACUUAAUAUUAUUGAGC...
8654799        8836  CUCUUAGUCUCCCUACGCCUUGAUAAUAGACUUAAUAUUAUUGAGC...
8654800        8836  CUCUUAGUCUCCCUACGCCUUGAUAAUAGACUUAAUAUUAUUGAGC...
8654801        8836  CUCUUAGUCUCCCUACGCCUUGAUAAUAGACUUAAUAUUAUUGAGC...
8654802        8836  CUCUUAGUCUCCCUACGCCUUGAUAAUAGACUUAAUAUUAUUGAGC...

[8654803 rows x 2 columns]

In [2]:
import pandas as pd

samples = pd.read_parquet("/home/tds122/coaster/data/samples_yeast.parquet")

samples

,chr,strand,start_seq,end_seq,start_coverage,end_coverage,input_sequence,fold
0,NC_001133.9,+,1,4000,1,3000,CCACACCACACCCACACACCCACACACCACACCACACACCACACCA...,train
1,NC_001133.9,+,2001,7000,3001,6000,GGGCGGCTTGGAACATGTAGTATTGGGCTAAGTGAGCTCTGATATC...,train
2,NC_001133.9,+,5001,10000,6001,9000,ATTTATCTTTTATAAAAAACCCTTGTTCTACTGACAGGATGGAATA...,train
3,NC_001133.9,+,8001,13000,9001,12000,CTAATTTCATCATCAGTTAAGAAAATAGAATAACAGTTGTATGGGT...,train
4,NC_001133.9,+,10389,15388,11389,14388,CATGTATATAGAAAATCACAGTACAAAAATTTTGAATTTATGTATA...,train
...,...,...,...,...,...,...,...,...
8832,NC_001148.4,-,12904,17903,13904,16903,TTGTAATTATTCCTGCTTAAAATGAATAAAGAAAGTACAACACAAT...,train
8833,NC_001148.4,-,9918,14917,10918,13917,AGTCATGCCAGCAAGATTTAAGATTTTCTTTATTTAGTGTTTATAT...,train
8834,NC_001148.4,-,6918,11917,7918,10917,TAAGAGATATTAGCGCTCTTTTTGGAGTCATTGCAAGGCCAGTTTT...,train
8835,NC_001148.4,-,3918,8917,4918,7917,TTAGAATAACGTAATCGTATCAACGAATCCACTAGGCGCGCGTAAA...,train
8836,NC_001148.4,-,918,5917,1918,4917,GTTGTGCTTGAAGGGGACAGACAGTCGCTTATCTTAGTGAGATTTC...,train